// ESLint configuration for WTR Lab Term Replacer
// Includes support for Tampermonkey/Greasemonkey, browser, and Node.js globals

module.exports = [
  {
    ignores: ['dist/*', 'node_modules/*', '*.user.js', 'config/*']
  },
  {
    languageOptions: {
      globals: {
        // Tampermonkey/Greasemonkey globals
        'GM_info': 'readonly',
        'GM_getValue': 'readonly',
        'GM_setValue': 'readonly',
        'GM_deleteValue': 'readonly',
        'GM_listValues': 'readonly',
        'GM_addValueChangeListener': 'readonly',
        'GM_removeValueChangeListener': 'readonly',
        'GM_log': 'readonly',
        'GM_getTab': 'readonly',
        'GM_saveTab': 'readonly',
        'GM_getTabs': 'readonly',
        'GM_onUrlChange': 'readonly',
        'GM_registerMenuCommand': 'readonly',
        'GM_unregisterMenuCommand': 'readonly',
        'GM_openInTab': 'readonly',
        'GM_xmlhttpRequest': 'readonly',
        'GM_download': 'readonly',
        'GM_cookie': 'readonly',
        'GM_setClipboard': 'readonly',
        'GM_notification': 'readonly',
        'GM_wait': 'readonly',
        'GM_getResourceText': 'readonly',
        'GM_getResourceURL': 'readonly',
        'GM_addElement': 'readonly',
        'GM_deleteElement': 'readonly',
        'GM_xmlhttpRequest': 'readonly',
        'GM_notification': 'readonly',
        'GM_addStyle': 'readonly',
        'GM_manifest': 'readonly',
        'GM_updateScript': 'readonly',
        'GM_toFile': 'readonly',
        'GM_toURL': 'readonly',
        'GM_fromFile': 'readonly',
        'GM_fromURL': 'readonly',
        'GM_unload': 'readonly',
        'GM_getScriptState': 'readonly',
        'GM_setScriptState': 'readonly',
        'GM_runAt': 'readonly',
        'GM_getMetadata': 'readonly',
        'GM_test': 'readonly',
        'GM_deleteScript': 'readonly',
        'GM_name': 'readonly',
        'GM_value': 'readonly',
        'GM_keys': 'readonly',
        'GM_putValue': 'readonly',
        'GM_getValue': 'readonly',
        'GM_deleteValue': 'readonly',
        'GM_listValues': 'readonly',
        'GM_addValueChangeListener': 'readonly',
        'GM_removeValueChangeListener': 'readonly',
        'GM_info': 'readonly',
        'GM_log': 'readonly',
        'GM_getTab': 'readonly',
        'GM_saveTab': 'readonly',
        'GM_getTabs': 'readonly',
        'GM_onUrlChange': 'readonly',
        'GM_registerMenuCommand': 'readonly',
        'GM_unregisterMenuCommand': 'readonly',
        'GM_openInTab': 'readonly',
        'GM_xmlhttpRequest': 'readonly',
        'GM_download': 'readonly',
        'GM_cookie': 'readonly',
        'GM_setClipboard': 'readonly',
        'GM_notification': 'readonly',
        'GM_wait': 'readonly',
        'GM_getResourceText': 'readonly',
        'GM_getResourceURL': 'readonly',
        'GM_addElement': 'readonly',
        'GM_deleteElement': 'readonly',
        'GM_xmlhttpRequest': 'readonly',
        'GM_notification': 'readonly',
        'GM_addStyle': 'readonly',
        'GM_manifest': 'readonly',
        'GM_updateScript': 'readonly',
        'GM_toFile': 'readonly',
        'GM_toURL': 'readonly',
        'GM_fromFile': 'readonly',
        'GM_fromURL': 'readonly',
        'GM_unload': 'readonly',
        'GM_getScriptState': 'readonly',
        'GM_setScriptState': 'readonly',
        'GM_runAt': 'readonly',
        'GM_getMetadata': 'readonly',
        'GM_test': 'readonly',
        'GM_deleteScript': 'readonly',
        'GM_name': 'readonly',
        'GM_value': 'readonly',
        'GM_keys': 'readonly',
        'GM_putValue': 'readonly',
        
        // jQuery $ global
        '$': 'readonly',
        
        // Browser globals
        'window': 'readonly',
        'document': 'readonly',
        'navigator': 'readonly',
        'location': 'readonly',
        'history': 'readonly',
        'localStorage': 'readonly',
        'sessionStorage': 'readonly',
        'console': 'readonly',
        'setTimeout': 'readonly',
        'setInterval': 'readonly',
        'clearTimeout': 'readonly',
        'clearInterval': 'readonly',
        'fetch': 'readonly',
        'XMLHttpRequest': 'readonly',
        'MutationObserver': 'readonly',
        'IntersectionObserver': 'readonly',
        'ResizeObserver': 'readonly',
        'Promise': 'readonly',
        'Map': 'readonly',
        'Set': 'readonly',
        'WeakMap': 'readonly',
        'WeakSet': 'readonly',
        'ArrayBuffer': 'readonly',
        'DataView': 'readonly',
        'Int8Array': 'readonly',
        'Uint8Array': 'readonly',
        'Uint8ClampedArray': 'readonly',
        'Int16Array': 'readonly',
        'Uint16Array': 'readonly',
        'Int32Array': 'readonly',
        'Uint32Array': 'readonly',
        'Float32Array': 'readonly',
        'Float64Array': 'readonly',
        'BigInt64Array': 'readonly',
        'BigUint64Array': 'readonly',
        'Atomics': 'readonly',
        'SharedArrayBuffer': 'readonly',
        'TextEncoder': 'readonly',
        'TextDecoder': 'readonly',
        'URL': 'readonly',
        'URLSearchParams': 'readonly',
        'FormData': 'readonly',
        'Blob': 'readonly',
        'File': 'readonly',
        'FileReader': 'readonly',
        'FileReaderSync': 'readonly',
        'ArrayBuffer': 'readonly',
        'Object': 'readonly',
        'Function': 'readonly',
        'Boolean': 'readonly',
        'Number': 'readonly',
        'BigInt': 'readonly',
        'String': 'readonly',
        'Date': 'readonly',
        'RegExp': 'readonly',
        'Error': 'readonly',
        'EvalError': 'readonly',
        'RangeError': 'readonly',
        'ReferenceError': 'readonly',
        'SyntaxError': 'readonly',
        'TypeError': 'readonly',
        'URIError': 'readonly',
        'JSON': 'readonly',
        'Math': 'readonly',
        'Reflect': 'readonly',
        'Proxy': 'readonly',
        'Symbol': 'readonly',
        'BigInt': 'readonly',
        'globalThis': 'readonly',
        'Intl': 'readonly',
        'isFinite': 'readonly',
        'isNaN': 'readonly',
        'parseFloat': 'readonly',
        'parseInt': 'readonly',
        'decodeURI': 'readonly',
        'decodeURIComponent': 'readonly',
        'encodeURI': 'readonly',
        'encodeURIComponent': 'readonly',
        'escape': 'readonly',
        'unescape': 'readonly',
        
        // Node.js globals for development
        'require': 'readonly',
        'module': 'readonly',
        'exports': 'readonly',
        'console': 'readonly',
        'process': 'readonly',
        'Buffer': 'readonly',
        '__filename': 'readonly',
        '__dirname': 'readonly',
        'path': 'readonly',
        'fs': 'readonly',
        'os': 'readonly',
        'url': 'readonly',
        'querystring': 'readonly',
        'util': 'readonly',
        'http': 'readonly',
        'https': 'readonly',
        'crypto': 'readonly',
        'stream': 'readonly',
        'zlib': 'readonly',
        'events': 'readonly',
        'child_process': 'readonly',
        'worker_threads': 'readonly',
        'perf_hooks': 'readonly',
        'async_hooks': 'readonly',
        'cluster': 'readonly',
        'dgram': 'readonly',
        'dns': 'readonly',
        'domain': 'readonly',
        'readline': 'readonly',
        'repl': 'readonly',
        'string_decoder': 'readonly',
        'tls': 'readonly',
        'tty': 'readonly',
        'v8': 'readonly',
        'vm': 'readonly',
        'wasi': 'readonly',
        'worker_threads': 'readonly'
      }
    },
    rules: {
      // Unused variables and imports
      'no-unused-vars': ['error', {
        'vars': 'all',
        'args': 'after-used',
        'ignoreRestSiblings': true,
        'argsIgnorePattern': '^_'
      }],
      'no-unused-expressions': 'error',
      'no-undef': 'error',
      
      // General code quality
      'no-console': 'warn',
      'no-debugger': 'error',
      'no-alert': 'warn',
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-spacing': 'error',
      'comma-dangle': ['error', 'never'],
      'indent': ['error', 2],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'eol-last': ['error', 'always'],
      'no-trailing-spaces': 'error',
      'no-multiple-empty-lines': ['error', { 'max': 2 }],
      'max-len': ['warn', { 'code': 100 }],
      'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
      'space-infix-ops': 'error',
      'space-before-blocks': 'error',
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
      'curly': ['error', 'all'],
      'dot-notation': 'error',
      'eqeqeq': ['error', 'always'],
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-magic-numbers': ['warn', { 'ignore': [0, 1, -1, 2] }],
      'no-param-reassign': 'error',
      'no-return-assign': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': 'error',
      'no-useless-return': 'error',
      'prefer-template': 'error',
      'spaced-comment': ['error', 'always'],
      'yoda': 'error',
      
      // ES6+ features
      'object-shorthand': 'error',
      'prefer-destructuring': ['error', {
        'object': true,
        'array': true
      }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'rest-spread-spacing': 'error',
      'yield-star-spacing': ['error', 'after'],
      
      // Error handling
      'handle-callback-err': 'error',
      'no-throw-literal': 'error'
    }
  }
];